{
    'name': 'إدارة المكتب القانوني',
    'version': '19.0.1.0.0',
    'category': 'Legal',
    'summary': 'إدارة القضايا والجلسات والاستشارات القانونية',
    'author': 'leapai.ai',
    'website': 'https://leapai.ai',
    'license': 'LGPL-3',
    'depends': ['account', 'mail', 'contacts'],
    'data': [
        'security/law_security.xml',
        'security/ir.model.access.csv',
        'data/law_sequences.xml',
        'views/law_case_views.xml',
        'views/law_hearing_views.xml',
        'views/law_time_entry_views.xml',
        'views/law_consultation_views.xml',
        'views/law_dashboard_views.xml',
        'views/law_reports_views.xml',
        'reports/law_case_report.xml',
        'views/law_menus.xml',
    ],
    'demo': ['demo/law_demo.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/icon.png'],
}
